Ported the version at branch slurm-scsf-sim-v14 to SLURM 17.11

diff --git a/testsuite/expect/regression b/testsuite/expect/regression
--- a/testsuite/expect/regression
+++ b/testsuite/expect/regression
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 ############################################################################
 # Purpose: Test of SLURM functionality
 #          Executes the full battery of tests.
@@ -13,8 +13,8 @@
 # CODE-OCEC-09-009. All rights reserved.
 #
 # This file is part of SLURM, a resource management program.
-# For details, see <http://slurm.schedmd.com/>.
- # Please also read the supplied file: DISCLAIMER.
+# For details, see <https://slurm.schedmd.com/>.
+# Please also read the supplied file: DISCLAIMER.
 #
 # SLURM is free software; you can redistribute it and/or modify it under
 # the terms of the GNU General Public License as published by the Free
@@ -34,17 +34,27 @@
 FAILURES=0
 COMPLETIONS=0
 
+# Clear any environment variables that could break the tests.
+# Cray sets some squeue format options that break tests
+unset SQUEUE_ALL
+unset SQUEUE_SORT
+unset SQUEUE_FORMAT
+unset SQUEUE_FORMAT2
+
 # Make sure we are in the desired directory before possibly
 # removing files the user does not want to lose.
 if [ ! -x ./regression ]; then
 	echo "FAILURE: cd to 'testsuite/expect' before starting 'regression'"
 	exit 1
 fi
-if [ ! -x ./globals ]; then
+if [ ! -e ./globals ]; then
 	echo "FAILURE: 'globals' file not found"
 	exit 1
 fi
-
+if [ ! -x ./globals ]; then
+	echo "FAILURE: 'globals' file not executable"
+	exit 1
+fi
 
 # Remove any recently edited back-up files
 /bin/rm -f test*.*% test*input test*output test*error
@@ -53,7 +63,7 @@ fi
 /bin/date
 BEGIN_TIME=`date +%s`
 for major in `seq 1 100`; do
-	for minor in `seq 1 100`; do
+	for minor in `seq 1 150`; do
 		TEST=test${major}.${minor}
 		if [ ! -f ./$TEST ]; then continue; fi
 
@@ -68,6 +78,7 @@ for major in `seq 1 100`; do
 			echo "$TEST FAILURE"
 			grep "$TEST " README >& 2
 			echo "=============" >& 2
+			if [ -f ./slurm_status ]; then ./slurm_status; fi
 		fi
 		/bin/echo "============================================"
 	done
